// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: building_type.sql

package db

import (
	"context"
)

const createBuildingType = `-- name: CreateBuildingType :one
INSERT INTO registration.building_type (
    description
) VALUES (
    $1
)
RETURNING id, description
`

func (q *Queries) CreateBuildingType(ctx context.Context, description string) (RegistrationBuildingType, error) {
	row := q.db.QueryRowContext(ctx, createBuildingType, description)
	var i RegistrationBuildingType
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const deleteBuildingType = `-- name: DeleteBuildingType :exec
DELETE FROM registration.building_type
WHERE id = $1
`

func (q *Queries) DeleteBuildingType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBuildingType, id)
	return err
}

const getBuildingType = `-- name: GetBuildingType :one
SELECT id, description FROM registration.building_type
WHERE id = $1
`

func (q *Queries) GetBuildingType(ctx context.Context, id int32) (RegistrationBuildingType, error) {
	row := q.db.QueryRowContext(ctx, getBuildingType, id)
	var i RegistrationBuildingType
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const listBuildingTypes = `-- name: ListBuildingTypes :many
SELECT id, description FROM registration.building_type
ORDER BY description
LIMIT $1 OFFSET $2
`

type ListBuildingTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBuildingTypes(ctx context.Context, arg ListBuildingTypesParams) ([]RegistrationBuildingType, error) {
	rows, err := q.db.QueryContext(ctx, listBuildingTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationBuildingType
	for rows.Next() {
		var i RegistrationBuildingType
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildingType = `-- name: UpdateBuildingType :one
UPDATE registration.building_type
SET
  description = $2
WHERE id = $1
RETURNING id, description
`

type UpdateBuildingTypeParams struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

func (q *Queries) UpdateBuildingType(ctx context.Context, arg UpdateBuildingTypeParams) (RegistrationBuildingType, error) {
	row := q.db.QueryRowContext(ctx, updateBuildingType, arg.ID, arg.Description)
	var i RegistrationBuildingType
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}
