// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type AccessUser struct {
	ID     int32          `json:"id"`
	Login  string         `json:"login"`
	Email  string         `json:"email"`
	Name   string         `json:"name"`
	Phone  sql.NullString `json:"phone"`
	Hash   string         `json:"hash"`
	Active bool           `json:"active"`
}

type AccessUserCondo struct {
	IDUser     int32 `json:"id_user"`
	IDCondo    int32 `json:"id_condo"`
	IDUserType int32 `json:"id_user_type"`
}

type AccessUserType struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type FinanceMovementType struct {
	ID                int32         `json:"id"`
	Description       string        `json:"description"`
	Direction         string        `json:"direction"`
	IDDefaultSupplier sql.NullInt32 `json:"id_default_supplier"`
}

type RegistrationBuilding struct {
	ID             int32  `json:"id"`
	IDCondo        int32  `json:"id_condo"`
	IDBuildingType int32  `json:"id_building_type"`
	Description    string `json:"description"`
}

type RegistrationBuildingType struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type RegistrationCondo struct {
	ID          int32          `json:"id"`
	IDCondoType int32          `json:"id_condo_type"`
	Name        string         `json:"name"`
	Nickname    string         `json:"nickname"`
	Address1    sql.NullString `json:"address1"`
	Address2    sql.NullString `json:"address2"`
	Phone1      sql.NullString `json:"phone1"`
	Phone2      sql.NullString `json:"phone2"`
	Email       string         `json:"email"`
	Cnpj        int64          `json:"cnpj"`
}

type RegistrationCondoType struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type RegistrationSupplier struct {
	ID             int32  `json:"id"`
	IDSupplierType int32  `json:"id_supplier_type"`
	Description    string `json:"description"`
}

type RegistrationSupplierType struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type RegistrationUnity struct {
	ID          int32  `json:"id"`
	IDBuilding  int32  `json:"id_building"`
	IDUnityType int32  `json:"id_unity_type"`
	UnityNumber string `json:"unity_number"`
}

type RegistrationUnityType struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}
