// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: unity_type.sql

package db

import (
	"context"
)

const createUnityType = `-- name: CreateUnityType :one
INSERT INTO registration.unity_type (
    description
) VALUES (
    $1
)
RETURNING id, description
`

func (q *Queries) CreateUnityType(ctx context.Context, description string) (RegistrationUnityType, error) {
	row := q.db.QueryRowContext(ctx, createUnityType, description)
	var i RegistrationUnityType
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const deleteUnityType = `-- name: DeleteUnityType :exec
DELETE FROM registration.unity_type
WHERE id = $1
`

func (q *Queries) DeleteUnityType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUnityType, id)
	return err
}

const getUnityType = `-- name: GetUnityType :one
SELECT id, description FROM registration.unity_type
WHERE id = $1
`

func (q *Queries) GetUnityType(ctx context.Context, id int32) (RegistrationUnityType, error) {
	row := q.db.QueryRowContext(ctx, getUnityType, id)
	var i RegistrationUnityType
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const listUnityTypes = `-- name: ListUnityTypes :many
SELECT id, description FROM registration.unity_type
ORDER BY description
LIMIT $1 OFFSET $2
`

type ListUnityTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnityTypes(ctx context.Context, arg ListUnityTypesParams) ([]RegistrationUnityType, error) {
	rows, err := q.db.QueryContext(ctx, listUnityTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationUnityType
	for rows.Next() {
		var i RegistrationUnityType
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnityType = `-- name: UpdateUnityType :one
UPDATE registration.unity_type
SET
  description = $2
WHERE id = $1
RETURNING id, description
`

type UpdateUnityTypeParams struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

func (q *Queries) UpdateUnityType(ctx context.Context, arg UpdateUnityTypeParams) (RegistrationUnityType, error) {
	row := q.db.QueryRowContext(ctx, updateUnityType, arg.ID, arg.Description)
	var i RegistrationUnityType
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}
